title: Trooper Transfer Studio
logo: /assets/img/logo.png
description: Main Website

url: https://trooper-transfer.github.io
#google_analytics:

patreon: https://patreon.com/the_perfect_childhood?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
instagram: https://www.instagram.com/troopertransfer?igsh=aThsYmM3bmpkencw
bluesky: https://bsky.app/profile/trooper-transfer.bsky.social
email: mailto:studio@trooper-transfer.com?subject=Requesting%20Information